DROP TABLE IF EXISTS PUBLIC.COMMENTS;
DROP TABLE IF EXISTS PUBLIC.BOOKINGS;
DROP TABLE IF EXISTS PUBLIC.ITEMS;
DROP TABLE IF EXISTS PUBLIC.ITEM_REQUESTS;
DROP TABLE IF EXISTS PUBLIC.USERS;

CREATE TABLE PUBLIC.USERS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(200) NOT NULL,
	CONSTRAINT USERS_PK PRIMARY KEY (ID),
	CONSTRAINT USERS_UNIQUE UNIQUE (EMAIL)
);

CREATE TABLE PUBLIC.ITEM_REQUESTS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	DESCRIPTION VARCHAR_IGNORECASE(1000) NOT NULL,
	REQUESTOR INTEGER NOT NULL,
	CREATED TIMESTAMP NOT NULL,
	CONSTRAINT ITEM_REQUEST_PK PRIMARY KEY (ID),
	CONSTRAINT ITEM_REQUESTS_USERS_FK FOREIGN KEY (REQUESTOR) REFERENCES PUBLIC.USERS(ID)
);

CREATE TABLE PUBLIC.ITEMS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME VARCHAR_IGNORECASE(200) NOT NULL,
	DESCRIPTION VARCHAR_IGNORECASE(1500),
	OWNER INTEGER NOT NULL,
	NUMBER_OF_RENTALS INTEGER DEFAULT 0,
	AVAILABLE BOOLEAN DEFAULT false,
	REQUEST INTEGER,
	CONSTRAINT NEWTABLE_PK PRIMARY KEY (ID),
	CONSTRAINT ITEMS_USERS_FK FOREIGN KEY (OWNER) REFERENCES PUBLIC.USERS(ID),
	CONSTRAINT ITEMS_ITEM_REQUESTS_FK FOREIGN KEY (REQUEST) REFERENCES PUBLIC.ITEM_REQUESTS(ID)
);

CREATE TABLE PUBLIC.BOOKINGS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	START_TIME TIMESTAMP,
	END_TIME TIMESTAMP,
	ITEM INTEGER NOT NULL,
	BOOKER INTEGER NOT NULL,
	STATUS CHARACTER VARYING(16),
	CONSTRAINT BOOKINGS_PK PRIMARY KEY (ID),
	CONSTRAINT BOOKINGS_ITEMS_FK FOREIGN KEY (ITEM) REFERENCES PUBLIC.ITEMS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT BOOKINGS_USERS_FK FOREIGN KEY (BOOKER) REFERENCES PUBLIC.USERS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE PUBLIC.COMMENTS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	AUTHOR INTEGER NOT NULL,
	ITEM INTEGER NOT NULL,
	TEXT CHARACTER VARYING(1000),
	CREATED TIMESTAMP NOT NULL,
	CONSTRAINT COMMENTS_PK PRIMARY KEY (ID),
	CONSTRAINT COMMENTS_ITEMS_FK FOREIGN KEY (ITEM) REFERENCES PUBLIC.ITEMS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT COMMENTS_USERS_FK FOREIGN KEY (AUTHOR) REFERENCES PUBLIC.USERS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);